export const CHANGE_SEACRH_FIELD = 'CHANGE_SEACRH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';

export const ROBOTS_DATA_API = 'https://jsonplaceholder.typicode.com/users';